- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Assign.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoClaw.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Autobot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Auton.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/DriveTile.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/DriveTrain.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Drone.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/IntakeClaw.java
- TeamCode/src/main/res/xml/bobobot.xml
Allows for Bobot to move # tiles
> Tile Motion

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Assign.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoClaw.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Autobot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/DriveTrain.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/IntakeClaw.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/TurnTile.java
> Bobot Dashboard

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Assign.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoSystems/AutoClaw.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoSystems/AutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoSystems/Mechanisms.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoTiles/DriveTile.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoTiles/StrafeTile.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoTiles/TurnTile.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Auton.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Bots/Autobot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Bots/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/TeleSystems/DriveTrain.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/TeleSystems/Drone.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/TeleSystems/IntakeClaw.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/goldenduck/GoldenDuckOpMode.java
Queue works
Telemetry Showing Error
> More Autonomous Stuff

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoSystems/AutoClaw.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoSystems/Mechanisms.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Auton.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Bots/Autobot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/TeleSystems/IntakeClaw.java
> Auton Telemetry

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoActions/DriveTile.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoActions/Mechanisms.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoActions/StrafeTile.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoActions/TurnTile.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Bots/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/IMU.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/SensorBNO055IMU.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/TeleOpSystems/IntakeClaw.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/TeleOpSystems/Joint.java
- TeamCode/src/main/res/xml/bobobot.xml
> IMU Implementation for Bobot

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Assign.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoActions/Mechanisms.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoActions/TurnTile.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoSystems/AutoClaw.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoSystems/AutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/TeleOpSystems/DriveTrain.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/TeleOpSystems/IntakeClaw.java
These are just methods to add a list of actions for Bobot depending on the starting position for matches with respect to alliance. This will be tested immediately at the Meet before 3734's matches.
> Pre Meet Autonomous Scenario Code.

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Assign.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoActions/DiagTile.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/AutoActions/TurnTile.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/RoadRunning/DriveConstants.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/RoadRunning/ProtoMecanumDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/TeleOpSystems/IntakeClaw.java
- Drive Constants 
- Mecanum Drive
> Added two Classes to begin RoadRunner Quickstart.

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Autonomous.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboDebugOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboRunnerOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/MotorDebug.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/RoadRunning/MecanumDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/RunnerBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Subsystems/DriveTrain.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Utilities/BobotPosition.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Utilities/Toggle.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/csbot/rr_stuff/tuning/ManualFeedbackTuner.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/csbot/rr_stuff/tuning/TuningOpModes.java
- Tuning for the Robot
- Having it so it can be seen on the Field in TeleOp.
> Tuning and Robot Field Drawing

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/BoboRunnerOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/RoadRunning/MecanumDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Subsystems/Drone.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Subsystems/Intake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Subsystems/RunnerBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/bobobot/Utilities/Toggle.java
> Intake and Subsystem Changes

- MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepStrafeTesting.java
> Meep Meep Strafing; Parking for Audience and Backdrop

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/ri2d/Outtake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/ri2d/Swerve.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/samples/SensorTest_Ultrasonic.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/samples/US_016Sensor.java
> Ultrasonic Sensor

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/r2v2/R2V2.java
> Sample Pull Request

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/core/Robot.java
> commented out claw

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/core/Robot.java
Haven't fine tuned the values for the limits, will test on Monday.
> Gamepad Adjustments and Limits

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/core/CoreAuton.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/core/Robot.java
pulled Nirjha's code so that we could have a collaboration branch. Will do pull requests from here instead of individually. More efficient and allows for teamwork, includes testing autonomous.
> Collaboration Branch 

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/deepthought/subsystem/samplers/RollerClaw.java
- TeamCode/src/main/res/xml/rollerclaw.xml
> rollerclaw.java functionality

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/core/AutonCode2.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/core/Robot.java
- Update AutonCode2.java
- strategy and turning func
- starting ticks
- stuff
- rotation in claw and minor edits
- Autonomous
> Autonomous

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/core/AutonCode2.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/core/Robot.java
> working specimen #1

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/giant/GiantAuton2.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/giant/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/giant/giantOpMode.java
> code from semi, 2 autons (both kinda bad), new/tweaked driver presets

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/giant/GiantAuton.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/giant/GiantAuton2.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/giant/GiantAutonNew.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/giant/Robot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/giant/TestAuton.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/giant/giantOpMode.java
> 2 autons with semi-tuned PID, new driver control button assignment

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/swerve/TriSwerve.java
- TeamCode/src/main/res/xml/triswerve.xml
> digicolorsensor

- TeamCode/src/main/assets/configs/swervo.xml
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/swerve/TriSwerve.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/swerve/TriSwerveOp.java
> quicktrip changes

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/swerve/TriSwerve.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/swerve/TriSwerveOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robots/testLeg.java
triswerve turn in place works now
> TriSwerve turn
